### ISSUE TITLE
Error while creating a table

### ISSUE THREAD

**Issue by srujanaparupudi** [Srujana08/BVRITH-WISE7-Team4#1]
Asokan, 

wise_pyramid is my virtual environment and sample_project is my project name
So in "models" directory i wrote the code for the tables in the database. 
user.py is a table that stores the username, role of the user and the encrypted format of the password. 
So when i am trying to initialize the database i got the following error : 
1) 1406 : data too long for the column for the hashed password
I tried all the possible datatypes and ended up getting the same error. Could you please help me with this issue, 

Thank you

![error](https://cloud.githubusercontent.com/assets/18423202/21809690/d373e036-d76e-11e6-8568-a986caa90759.png)
![user_py](https://cloud.githubusercontent.com/assets/18423202/21809691/d3756866-d76e-11e6-877c-59e9496c32f4.png)

**Comment by pasokan** [comment]
What is the size of the passwdhash column in the db? What is the
corresponding entry in models.py?

**Comment by srujanaparupudi** [comment]
I got to know where i went wrong Asokan. 
In the database size of password_hash column was 10. 
whereas in models.py it is different, 
Thank you
